<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ImportarDatosSeeder extends Seeder
{
    public function run(): void
    {
        // Desactivar restricciones de clave foránea
        DB::statement('SET session_replication_role = replica;');

        // ==========================================
        // 1. EMPRESAS
        // ==========================================
        DB::table('empresa')->insert([
            ['id_empresa' => 1, 'nombre' => 'Empresa Juan', 'nombre_comercial' => 'Juan Prendas', 'rfc' => 'JUAN123456ABC', 'telefono' => '5551234567', 'email' => 'juan@empresa.com', 'direccion' => 'Calle Principal 123', 'ciudad' => 'Ciudad de México', 'estado' => 'CDMX', 'codigo_postal' => '12345', 'logo_url' => null, 'precio_oro_gramo' => 850.00, 'precio_oro_onza' => null, 'ultima_actualizacion_oro' => null, 'activo' => 1, 'id_plan' => 3, 'fecha_registro' => '2026-06-25 09:55:26', 'fecha_inicio_plan' => '2026-06-25', 'fecha_fin_plan' => '2026-07-25', 'plan_activo' => 1],
            ['id_empresa' => 2, 'nombre' => 'Empresa Tula', 'nombre_comercial' => 'Tula Empeños', 'rfc' => 'TULA987654XYZ', 'telefono' => '5557654321', 'email' => 'tula@empresa.com', 'direccion' => 'Av. Reforma 456', 'ciudad' => 'Tula', 'estado' => 'Hidalgo', 'codigo_postal' => '67890', 'logo_url' => null, 'precio_oro_gramo' => 850.00, 'precio_oro_onza' => null, 'ultima_actualizacion_oro' => null, 'activo' => 1, 'id_plan' => null, 'fecha_registro' => '2026-06-25 09:55:26', 'fecha_inicio_plan' => null, 'fecha_fin_plan' => null, 'plan_activo' => 1],
            ['id_empresa' => 3, 'nombre' => 'Empeños Express', 'nombre_comercial' => 'Express Empeños', 'rfc' => 'EXP123456ABC', 'telefono' => '5559876543', 'email' => 'express@empresa.com', 'direccion' => 'Boulevard Central 789', 'ciudad' => 'Guadalajara', 'estado' => 'Jalisco', 'codigo_postal' => '44100', 'logo_url' => null, 'precio_oro_gramo' => 850.00, 'precio_oro_onza' => null, 'ultima_actualizacion_oro' => null, 'activo' => 1, 'id_plan' => null, 'fecha_registro' => '2026-06-25 09:55:26', 'fecha_inicio_plan' => null, 'fecha_fin_plan' => null, 'plan_activo' => 1],
        ]);

        // ==========================================
        // 2. PLANES SAAS
        // ==========================================
        DB::table('planes_saas')->insert([
            ['id_plan' => 1, 'nombre' => 'Free Trial', 'clave' => 'free', 'precio_mensual' => 0.00, 'max_empleados' => 1, 'max_clientes' => 50, 'max_prendas' => 50, 'max_empenos_activos' => 5, 'dias_prueba' => 30, 'activo' => 1],
            ['id_plan' => 2, 'nombre' => 'Profesional', 'clave' => 'profesional', 'precio_mensual' => 999.00, 'max_empleados' => 5, 'max_clientes' => 1000, 'max_prendas' => 5000, 'max_empenos_activos' => 200, 'dias_prueba' => 0, 'activo' => 1],
            ['id_plan' => 3, 'nombre' => 'Premium', 'clave' => 'empresarial', 'precio_mensual' => 1499.00, 'max_empleados' => 20, 'max_clientes' => 10000, 'max_prendas' => 50000, 'max_empenos_activos' => 1000, 'dias_prueba' => 0, 'activo' => 1],
        ]);

        // ==========================================
        // 3. TASAS DE INTERÉS
        // ==========================================
        DB::table('tasas_interes')->insert([
            ['id_tasa' => 1, 'nombre' => 'Basico', 'porcentaje' => 5.00, 'plazo_dias' => 15, 'activo' => 1],
            ['id_tasa' => 2, 'nombre' => 'Estandar', 'porcentaje' => 8.00, 'plazo_dias' => 30, 'activo' => 1],
            ['id_tasa' => 3, 'nombre' => 'Premium', 'porcentaje' => 10.00, 'plazo_dias' => 45, 'activo' => 1],
            ['id_tasa' => 4, 'nombre' => 'Extendido', 'porcentaje' => 12.00, 'plazo_dias' => 60, 'activo' => 1],
            ['id_tasa' => 5, 'nombre' => 'Flexible', 'porcentaje' => 15.00, 'plazo_dias' => 90, 'activo' => 1],
        ]);

        // ==========================================
        // 4. PRECIO ORO
        // ==========================================
        DB::table('precio_oro')->insert([
            ['id_precio' => 1, 'precio_gramo_24k' => 2800.16, 'precio_gramo_22k' => 2566.81, 'precio_gramo_21k' => 2450.14, 'precio_gramo_18k' => 2100.12, 'precio_gramo_14k' => 1633.43, 'precio_gramo_10k' => 1166.73, 'precio_onza' => 87094.73, 'moneda' => 'MXN', 'fuente' => 'GoldAPI.io', 'fecha_actualizacion' => '2026-06-21 23:18:55'],
        ]);

        // ==========================================
        // 5. ROLES
        // ==========================================
        DB::table('rol')->insert([
            ['id_rol' => 1, 'id_empresa' => 1, 'nombre' => 'Administrador', 'descripcion' => 'Acceso total al sistema con todos los permisos', 'nivel' => 1],
            ['id_rol' => 2, 'id_empresa' => 1, 'nombre' => 'Gerente', 'descripcion' => 'Gestión de clientes, empeños y operaciones', 'nivel' => 2],
            ['id_rol' => 3, 'id_empresa' => 1, 'nombre' => 'Cajero', 'descripcion' => 'Operaciones de caja y pagos', 'nivel' => 3],
            ['id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Cliente', 'descripcion' => 'Portal de clientes - visualización básica', 'nivel' => 4],
            ['id_rol' => 5, 'id_empresa' => 2, 'nombre' => 'Administrador', 'descripcion' => 'Acceso total al sistema con todos los permisos', 'nivel' => 1],
            ['id_rol' => 6, 'id_empresa' => 2, 'nombre' => 'Gerente', 'descripcion' => 'Gestión de clientes, empeños y operaciones', 'nivel' => 2],
            ['id_rol' => 7, 'id_empresa' => 2, 'nombre' => 'Cajero', 'descripcion' => 'Operaciones de caja y pagos', 'nivel' => 3],
            ['id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Cliente', 'descripcion' => 'Portal de clientes - visualización básica', 'nivel' => 4],
            ['id_rol' => 9, 'id_empresa' => 3, 'nombre' => 'Administrador', 'descripcion' => 'Acceso total al sistema con todos los permisos', 'nivel' => 1],
            ['id_rol' => 10, 'id_empresa' => 3, 'nombre' => 'Gerente', 'descripcion' => 'Gestión de clientes, empeños y operaciones', 'nivel' => 2],
            ['id_rol' => 11, 'id_empresa' => 3, 'nombre' => 'Cajero', 'descripcion' => 'Operaciones de caja y pagos', 'nivel' => 3],
            ['id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Cliente', 'descripcion' => 'Portal de clientes - visualización básica', 'nivel' => 4],
        ]);

        // ==========================================
        // 6. USUARIOS (contraseña: 'password')
        // ==========================================
        $password = Hash::make('password');
        DB::table('usuario')->insert([
            ['id_usuario' => 1, 'id_rol' => 1, 'id_empresa' => 1, 'nombre' => 'Administrador Juan Prendas', 'correo' => 'juanprendas@admin.com', 'contrasena' => $password, 'telefono' => '607-889-5746', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:26', 'ultimo_acceso' => null],
            ['id_usuario' => 2, 'id_rol' => 2, 'id_empresa' => 1, 'nombre' => 'Gerente Juan Prendas', 'correo' => 'juanprendas.gerente@admin.com', 'contrasena' => $password, 'telefono' => '+1-540-876-0628', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:26', 'ultimo_acceso' => null],
            ['id_usuario' => 3, 'id_rol' => 3, 'id_empresa' => 1, 'nombre' => 'Cajero Juan Prendas', 'correo' => 'juanprendas.cajero@admin.com', 'contrasena' => $password, 'telefono' => '+1-518-644-9777', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 4, 'id_rol' => 2, 'id_empresa' => 1, 'nombre' => 'Princess Hodkiewicz', 'correo' => 'bernhard.jerod@example.com', 'contrasena' => $password, 'telefono' => '1-541-338-6362', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 5, 'id_rol' => 2, 'id_empresa' => 1, 'nombre' => 'Abagail Gorczany', 'correo' => 'vstokes@example.net', 'contrasena' => $password, 'telefono' => '248.608.9942', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 6, 'id_rol' => 3, 'id_empresa' => 1, 'nombre' => 'Annie Konopelski IV', 'correo' => 'ratke.jeffry@example.org', 'contrasena' => $password, 'telefono' => '1-458-717-9000', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 7, 'id_rol' => 3, 'id_empresa' => 1, 'nombre' => 'Rachael Barrows', 'correo' => 'ramiro.wuckert@example.net', 'contrasena' => $password, 'telefono' => '+1.262.360.0930', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 8, 'id_rol' => 3, 'id_empresa' => 1, 'nombre' => 'Randal Luettgen', 'correo' => 'dante.mitchell@example.com', 'contrasena' => $password, 'telefono' => '1-937-267-1795', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 9, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Brian Zemlak', 'correo' => 'abel05@example.net', 'contrasena' => $password, 'telefono' => '+1-475-745-3707', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 10, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Alycia Smith', 'correo' => 'klind@example.org', 'contrasena' => $password, 'telefono' => '1-341-428-4425', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 11, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Claudie Stanton', 'correo' => 'tina11@example.org', 'contrasena' => $password, 'telefono' => '308-848-1274', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 12, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Amelie Powlowski', 'correo' => 'antwon52@example.net', 'contrasena' => $password, 'telefono' => '+19302466106', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 13, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Jakob Hackett', 'correo' => 'vergie38@example.net', 'contrasena' => $password, 'telefono' => '(580) 212-1311', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 14, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Ilene Kutch', 'correo' => 'goodwin.kelvin@example.org', 'contrasena' => $password, 'telefono' => '360.271.5133', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 15, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Anita Gusikowski', 'correo' => 'candice69@example.org', 'contrasena' => $password, 'telefono' => '+1-401-495-7066', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 16, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Nolan Cremin', 'correo' => 'eanderson@example.com', 'contrasena' => $password, 'telefono' => '320.408.3858', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:27', 'ultimo_acceso' => null],
            ['id_usuario' => 17, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Adrienne Bins', 'correo' => 'ephraim.anderson@example.net', 'contrasena' => $password, 'telefono' => '212-270-9508', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 18, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Chelsey Bauch', 'correo' => 'thompson.herman@example.org', 'contrasena' => $password, 'telefono' => '(319) 816-4012', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 19, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Evelyn Zemlak', 'correo' => 'schneider.ruby@example.com', 'contrasena' => $password, 'telefono' => '323.239.0590', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 20, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Oscar Corwin', 'correo' => 'kirlin.felicity@example.com', 'contrasena' => $password, 'telefono' => '+1 (702) 637-6352', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 21, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Olin Baumbach', 'correo' => 'fkuphal@example.com', 'contrasena' => $password, 'telefono' => '+1 (252) 640-9235', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 22, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'General Haley', 'correo' => 'seamus33@example.org', 'contrasena' => $password, 'telefono' => '(478) 591-9077', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 23, 'id_rol' => 4, 'id_empresa' => 1, 'nombre' => 'Maybell Wisoky', 'correo' => 'makenzie39@example.org', 'contrasena' => $password, 'telefono' => '+12517453960', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 24, 'id_rol' => 5, 'id_empresa' => 2, 'nombre' => 'Administrador Tula Empeños', 'correo' => 'tulaempeños@admin.com', 'contrasena' => $password, 'telefono' => '219.525.1619', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 25, 'id_rol' => 6, 'id_empresa' => 2, 'nombre' => 'Gerente Tula Empeños', 'correo' => 'tulaempeños.gerente@admin.com', 'contrasena' => $password, 'telefono' => '+1-908-282-2963', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 26, 'id_rol' => 7, 'id_empresa' => 2, 'nombre' => 'Cajero Tula Empeños', 'correo' => 'tulaempeños.cajero@admin.com', 'contrasena' => $password, 'telefono' => '320-336-0668', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 27, 'id_rol' => 6, 'id_empresa' => 2, 'nombre' => 'Aracely Beatty', 'correo' => 'eve50@example.net', 'contrasena' => $password, 'telefono' => '347-634-5259', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 28, 'id_rol' => 6, 'id_empresa' => 2, 'nombre' => 'Evalyn Effertz', 'correo' => 'hallie.altenwerth@example.net', 'contrasena' => $password, 'telefono' => '1-347-588-0772', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 29, 'id_rol' => 7, 'id_empresa' => 2, 'nombre' => 'Miss Adella Williamson Sr.', 'correo' => 'gaylord16@example.org', 'contrasena' => $password, 'telefono' => '1-619-504-3585', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 30, 'id_rol' => 7, 'id_empresa' => 2, 'nombre' => 'Makayla Schamberger', 'correo' => 'reyna07@example.net', 'contrasena' => $password, 'telefono' => '(848) 763-5539', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 31, 'id_rol' => 7, 'id_empresa' => 2, 'nombre' => 'Reid Predovic', 'correo' => 'catharine51@example.net', 'contrasena' => $password, 'telefono' => '845-532-6183', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:28', 'ultimo_acceso' => null],
            ['id_usuario' => 32, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Skye Price', 'correo' => 'dorris.hahn@example.net', 'contrasena' => $password, 'telefono' => '(707) 297-0418', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 33, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Tavares Ritchie', 'correo' => 'west.letha@example.com', 'contrasena' => $password, 'telefono' => '(432) 305-2046', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 34, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Glen Parker', 'correo' => 'bogan.brody@example.com', 'contrasena' => $password, 'telefono' => '+1-320-534-3157', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 35, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Howard Stanton', 'correo' => 'gryan@example.com', 'contrasena' => $password, 'telefono' => '+19408734594', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 36, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Wade Morissette', 'correo' => 'stephania85@example.net', 'contrasena' => $password, 'telefono' => '(575) 360-6862', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 37, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Rod Bernhard', 'correo' => 'eemard@example.com', 'contrasena' => $password, 'telefono' => '559-548-8317', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 38, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Lucius Kiehn', 'correo' => 'ullrich.fatima@example.com', 'contrasena' => $password, 'telefono' => '980-365-2824', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 39, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Lester Mills', 'correo' => 'pierre92@example.org', 'contrasena' => $password, 'telefono' => '+1.321.424.8349', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 40, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Theodore Harvey', 'correo' => 'nader.crystal@example.net', 'contrasena' => $password, 'telefono' => '385-348-9756', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 41, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Maribel Nader', 'correo' => 'ynolan@example.org', 'contrasena' => $password, 'telefono' => '(970) 437-2430', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 42, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Foster Upton', 'correo' => 'elise.douglas@example.org', 'contrasena' => $password, 'telefono' => '854.257.2238', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 43, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Bertha Nolan', 'correo' => 'moore.maegan@example.net', 'contrasena' => $password, 'telefono' => '+14018766927', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 44, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Bessie Oberbrunner', 'correo' => 'gmante@example.com', 'contrasena' => $password, 'telefono' => '1-618-691-6841', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 45, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Renee Schroeder', 'correo' => 'pouros.benton@example.com', 'contrasena' => $password, 'telefono' => '+1.864.685.5732', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:29', 'ultimo_acceso' => null],
            ['id_usuario' => 46, 'id_rol' => 8, 'id_empresa' => 2, 'nombre' => 'Agustin Reichel', 'correo' => 'elody.schuster@example.com', 'contrasena' => $password, 'telefono' => '(231) 752-8014', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 47, 'id_rol' => 9, 'id_empresa' => 3, 'nombre' => 'Administrador Express Empeños', 'correo' => 'expressempeños@admin.com', 'contrasena' => $password, 'telefono' => '680-846-6784', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 48, 'id_rol' => 10, 'id_empresa' => 3, 'nombre' => 'Gerente Express Empeños', 'correo' => 'expressempeños.gerente@admin.com', 'contrasena' => $password, 'telefono' => '+1-854-371-2058', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 49, 'id_rol' => 11, 'id_empresa' => 3, 'nombre' => 'Cajero Express Empeños', 'correo' => 'expressempeños.cajero@admin.com', 'contrasena' => $password, 'telefono' => '762-238-0233', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 50, 'id_rol' => 10, 'id_empresa' => 3, 'nombre' => 'Dr. Destin Walsh IV', 'correo' => 'dkessler@example.net', 'contrasena' => $password, 'telefono' => '+1 (312) 380-7970', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 51, 'id_rol' => 10, 'id_empresa' => 3, 'nombre' => 'Mrs. Hannah Kerluke PhD', 'correo' => 'mertz.eliseo@example.org', 'contrasena' => $password, 'telefono' => '+14257878314', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 52, 'id_rol' => 11, 'id_empresa' => 3, 'nombre' => 'Ewald Johnston', 'correo' => 'igutmann@example.com', 'contrasena' => $password, 'telefono' => '(423) 424-5655', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 53, 'id_rol' => 11, 'id_empresa' => 3, 'nombre' => 'Presley Heathcote Sr.', 'correo' => 'shields.ryann@example.net', 'contrasena' => $password, 'telefono' => '+15087398885', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 54, 'id_rol' => 11, 'id_empresa' => 3, 'nombre' => 'Trisha Jakubowski', 'correo' => 'spinka.spencer@example.net', 'contrasena' => $password, 'telefono' => '+13256730998', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 55, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Veda Wisoky', 'correo' => 'zweimann@example.com', 'contrasena' => $password, 'telefono' => '754-867-0246', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 56, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Gaylord Emmerich', 'correo' => 'mitchell.anastacio@example.com', 'contrasena' => $password, 'telefono' => '+1.757.614.6046', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 57, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'River Collier', 'correo' => 'nathanial59@example.org', 'contrasena' => $password, 'telefono' => '540.429.1345', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 58, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Allie Grant', 'correo' => 'zaria65@example.net', 'contrasena' => $password, 'telefono' => '209-815-7048', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 59, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Cathy Leuschke', 'correo' => 'ifadel@example.org', 'contrasena' => $password, 'telefono' => '440-217-3664', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:30', 'ultimo_acceso' => null],
            ['id_usuario' => 60, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Dayton Daniel', 'correo' => 'jcarroll@example.net', 'contrasena' => $password, 'telefono' => '+16695351521', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:31', 'ultimo_acceso' => null],
            ['id_usuario' => 61, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Ceasar Rice', 'correo' => 'audie.doyle@example.org', 'contrasena' => $password, 'telefono' => '(216) 249-8871', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:31', 'ultimo_acceso' => null],
            ['id_usuario' => 62, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Zelda Beahan', 'correo' => 'thiel.chloe@example.net', 'contrasena' => $password, 'telefono' => '337-776-1080', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:31', 'ultimo_acceso' => null],
            ['id_usuario' => 63, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Herminio Stanton', 'correo' => 'jesse.mayert@example.com', 'contrasena' => $password, 'telefono' => '(380) 628-2623', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:31', 'ultimo_acceso' => null],
            ['id_usuario' => 64, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Lesly Langworth', 'correo' => 'qgislason@example.org', 'contrasena' => $password, 'telefono' => '1-509-250-7472', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:31', 'ultimo_acceso' => null],
            ['id_usuario' => 65, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Prince Wolf', 'correo' => 'chesley.morissette@example.net', 'contrasena' => $password, 'telefono' => '(940) 609-3754', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:31', 'ultimo_acceso' => null],
            ['id_usuario' => 66, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Stacey Schoen', 'correo' => 'mcclure.mathias@example.org', 'contrasena' => $password, 'telefono' => '+1-854-312-5517', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:31', 'ultimo_acceso' => null],
            ['id_usuario' => 67, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Ari Tromp', 'correo' => 'gtoy@example.org', 'contrasena' => $password, 'telefono' => '352.398.1359', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:31', 'ultimo_acceso' => null],
            ['id_usuario' => 68, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Andrew Von', 'correo' => 'langworth.gwendolyn@example.com', 'contrasena' => $password, 'telefono' => '+1 (747) 428-1394', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:31', 'ultimo_acceso' => null],
            ['id_usuario' => 69, 'id_rol' => 12, 'id_empresa' => 3, 'nombre' => 'Mose Greenholt', 'correo' => 'joany.waelchi@example.org', 'contrasena' => $password, 'telefono' => '859-776-0146', 'foto_perfil' => null, 'activo' => 1, 'fecha_registro' => '2026-06-25 09:55:31', 'ultimo_acceso' => null],
        ]);

        // ==========================================
        // 7. CLIENTES
        // ==========================================
        DB::table('clientes')->insert([
            ['id_cliente' => 1, 'id_usuario' => 9, 'id_empresa' => 1, 'nombre' => 'Brian', 'apellido' => 'Zemlak', 'telefono' => '1-601-593-0854', 'correo' => 'abel05@example.net', 'direccion' => '486 Larson Turnpike Apt. 685', 'codigo_postal' => '64551-3694', 'ciudad' => 'West Shaina', 'estado' => 'Hawaii', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 2, 'id_usuario' => 10, 'id_empresa' => 1, 'nombre' => 'Alycia', 'apellido' => 'Smith', 'telefono' => '414.827.9152', 'correo' => 'klind@example.org', 'direccion' => '235 Mitchell Viaduct', 'codigo_postal' => '69635', 'ciudad' => 'Giaborough', 'estado' => 'Alaska', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 3, 'id_usuario' => 11, 'id_empresa' => 1, 'nombre' => 'Claudie', 'apellido' => 'Stanton', 'telefono' => '+1.208.975.0457', 'correo' => 'tina11@example.org', 'direccion' => '840 Margret Trail', 'codigo_postal' => '47784-7112', 'ciudad' => 'Modestahaven', 'estado' => 'Wyoming', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 4, 'id_usuario' => 12, 'id_empresa' => 1, 'nombre' => 'Amelie', 'apellido' => 'Powlowski', 'telefono' => '+1 (501) 653-5071', 'correo' => 'antwon52@example.net', 'direccion' => '58845 Kiehn Cape', 'codigo_postal' => '21405-0345', 'ciudad' => 'Layneland', 'estado' => 'Washington', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 5, 'id_usuario' => 13, 'id_empresa' => 1, 'nombre' => 'Jakob', 'apellido' => 'Hackett', 'telefono' => '+1 (786) 994-6761', 'correo' => 'vergie38@example.net', 'direccion' => '9683 O\'Conner Spur Suite 992', 'codigo_postal' => '17369-1496', 'ciudad' => 'Effiemouth', 'estado' => 'Georgia', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 6, 'id_usuario' => 14, 'id_empresa' => 1, 'nombre' => 'Ilene', 'apellido' => 'Kutch', 'telefono' => '+16127444552', 'correo' => 'goodwin.kelvin@example.org', 'direccion' => '94130 Mollie Grove Suite 084', 'codigo_postal' => '88054-9117', 'ciudad' => 'West Letaland', 'estado' => 'Delaware', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 7, 'id_usuario' => 15, 'id_empresa' => 1, 'nombre' => 'Anita', 'apellido' => 'Gusikowski', 'telefono' => '248.310.1430', 'correo' => 'candice69@example.org', 'direccion' => '1693 Gust Row', 'codigo_postal' => '14617-3370', 'ciudad' => 'West Opalland', 'estado' => 'Kansas', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 8, 'id_usuario' => 16, 'id_empresa' => 1, 'nombre' => 'Nolan', 'apellido' => 'Cremin', 'telefono' => '(959) 342-7655', 'correo' => 'eanderson@example.com', 'direccion' => '46753 Kallie Points Apt. 396', 'codigo_postal' => '78407', 'ciudad' => 'Bahringermouth', 'estado' => 'Illinois', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 9, 'id_usuario' => 17, 'id_empresa' => 1, 'nombre' => 'Adrienne', 'apellido' => 'Bins', 'telefono' => '+16672962558', 'correo' => 'ephraim.anderson@example.net', 'direccion' => '8336 Rasheed Ports Apt. 094', 'codigo_postal' => '99872', 'ciudad' => 'Kenyattaton', 'estado' => 'Georgia', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 10, 'id_usuario' => 18, 'id_empresa' => 1, 'nombre' => 'Chelsey', 'apellido' => 'Bauch', 'telefono' => '+1-206-678-3355', 'correo' => 'thompson.herman@example.org', 'direccion' => '90838 Morris Loaf', 'codigo_postal' => '20907-9755', 'ciudad' => 'Nellieport', 'estado' => 'Illinois', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 11, 'id_usuario' => 19, 'id_empresa' => 1, 'nombre' => 'Evelyn', 'apellido' => 'Zemlak', 'telefono' => '678-798-9522', 'correo' => 'schneider.ruby@example.com', 'direccion' => '4196 Kreiger Isle Suite 820', 'codigo_postal' => '88641-4251', 'ciudad' => 'East Arvelbury', 'estado' => 'Alaska', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 12, 'id_usuario' => 20, 'id_empresa' => 1, 'nombre' => 'Oscar', 'apellido' => 'Corwin', 'telefono' => '814-403-6839', 'correo' => 'kirlin.felicity@example.com', 'direccion' => '92599 Anahi Drive Suite 484', 'codigo_postal' => '94858', 'ciudad' => 'Betteville', 'estado' => 'Delaware', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 13, 'id_usuario' => 21, 'id_empresa' => 1, 'nombre' => 'Olin', 'apellido' => 'Baumbach', 'telefono' => '1-231-753-2119', 'correo' => 'fkuphal@example.com', 'direccion' => '5928 Prosacco Tunnel Apt. 821', 'codigo_postal' => '03955-4435', 'ciudad' => 'Port Elmira', 'estado' => 'New Hampshire', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 14, 'id_usuario' => 22, 'id_empresa' => 1, 'nombre' => 'General', 'apellido' => 'Haley', 'telefono' => '+12513664064', 'correo' => 'seamus33@example.org', 'direccion' => '24810 Brent Place', 'codigo_postal' => '88074', 'ciudad' => 'Kautzerfurt', 'estado' => 'Kentucky', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 15, 'id_usuario' => 23, 'id_empresa' => 1, 'nombre' => 'Maybell', 'apellido' => 'Wisoky', 'telefono' => '+1 (863) 823-6423', 'correo' => 'makenzie39@example.org', 'direccion' => '6470 Alessia Courts Apt. 566', 'codigo_postal' => '10097-5014', 'ciudad' => 'Lake Odell', 'estado' => 'Pennsylvania', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 16, 'id_usuario' => 32, 'id_empresa' => 2, 'nombre' => 'Skye', 'apellido' => 'Price', 'telefono' => '986.972.1474', 'correo' => 'dorris.hahn@example.net', 'direccion' => '651 Cassandra Plain Apt. 065', 'codigo_postal' => '33831-0555', 'ciudad' => 'Soniashire', 'estado' => 'Louisiana', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 17, 'id_usuario' => 33, 'id_empresa' => 2, 'nombre' => 'Tavares', 'apellido' => 'Ritchie', 'telefono' => '1-478-713-8573', 'correo' => 'west.letha@example.com', 'direccion' => '7295 Lessie Station', 'codigo_postal' => '71524', 'ciudad' => 'New Svenmouth', 'estado' => 'Maine', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 18, 'id_usuario' => 34, 'id_empresa' => 2, 'nombre' => 'Glen', 'apellido' => 'Parker', 'telefono' => '1-781-794-4428', 'correo' => 'bogan.brody@example.com', 'direccion' => '9619 McClure Squares', 'codigo_postal' => '11758-9780', 'ciudad' => 'North Noemy', 'estado' => 'Kentucky', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 19, 'id_usuario' => 35, 'id_empresa' => 2, 'nombre' => 'Howard', 'apellido' => 'Stanton', 'telefono' => '+13205398048', 'correo' => 'gryan@example.com', 'direccion' => '785 Leuschke Cliffs Suite 616', 'codigo_postal' => '33481-6423', 'ciudad' => 'Mullerside', 'estado' => 'Wyoming', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 20, 'id_usuario' => 36, 'id_empresa' => 2, 'nombre' => 'Wade', 'apellido' => 'Morissette', 'telefono' => '980-666-6779', 'correo' => 'stephania85@example.net', 'direccion' => '7671 Thomas Points', 'codigo_postal' => '79629', 'ciudad' => 'Coleshire', 'estado' => 'Idaho', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 21, 'id_usuario' => 37, 'id_empresa' => 2, 'nombre' => 'Rod', 'apellido' => 'Bernhard', 'telefono' => '1-781-839-8700', 'correo' => 'eemard@example.com', 'direccion' => '40237 Kuvalis Ville', 'codigo_postal' => '22311-0596', 'ciudad' => 'Haleyberg', 'estado' => 'Florida', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 22, 'id_usuario' => 38, 'id_empresa' => 2, 'nombre' => 'Lucius', 'apellido' => 'Kiehn', 'telefono' => '1-304-808-5466', 'correo' => 'ullrich.fatima@example.com', 'direccion' => '46756 Jaycee Union', 'codigo_postal' => '61559-7206', 'ciudad' => 'Kassulkefort', 'estado' => 'Delaware', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 23, 'id_usuario' => 39, 'id_empresa' => 2, 'nombre' => 'Lester', 'apellido' => 'Mills', 'telefono' => '(484) 587-4535', 'correo' => 'pierre92@example.org', 'direccion' => '52319 Fritsch Brook', 'codigo_postal' => '59039', 'ciudad' => 'Shawnborough', 'estado' => 'Maine', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 24, 'id_usuario' => 40, 'id_empresa' => 2, 'nombre' => 'Theodore', 'apellido' => 'Harvey', 'telefono' => '1-681-945-0538', 'correo' => 'nader.crystal@example.net', 'direccion' => '98290 Metz Branch Suite 901', 'codigo_postal' => '18706', 'ciudad' => 'West Alessiabury', 'estado' => 'Louisiana', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 25, 'id_usuario' => 41, 'id_empresa' => 2, 'nombre' => 'Maribel', 'apellido' => 'Nader', 'telefono' => '(616) 667-6370', 'correo' => 'ynolan@example.org', 'direccion' => '61047 Kris Vista', 'codigo_postal' => '41037-6722', 'ciudad' => 'Tamaraview', 'estado' => 'Virginia', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 26, 'id_usuario' => 42, 'id_empresa' => 2, 'nombre' => 'Foster', 'apellido' => 'Upton', 'telefono' => '+1 (970) 466-9281', 'correo' => 'elise.douglas@example.org', 'direccion' => '524 Charlie Crossing Suite 802', 'codigo_postal' => '52204', 'ciudad' => 'Zenaborough', 'estado' => 'Mississippi', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 27, 'id_usuario' => 43, 'id_empresa' => 2, 'nombre' => 'Bertha', 'apellido' => 'Nolan', 'telefono' => '+1-786-834-0936', 'correo' => 'moore.maegan@example.net', 'direccion' => '546 Alysa Drive', 'codigo_postal' => '28571-2529', 'ciudad' => 'Skilesland', 'estado' => 'Oklahoma', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 28, 'id_usuario' => 44, 'id_empresa' => 2, 'nombre' => 'Bessie', 'apellido' => 'Oberbrunner', 'telefono' => '+1.434.336.5676', 'correo' => 'gmante@example.com', 'direccion' => '82561 Bethel Valley Apt. 545', 'codigo_postal' => '40326-7197', 'ciudad' => 'North Imelda', 'estado' => 'New Jersey', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 29, 'id_usuario' => 45, 'id_empresa' => 2, 'nombre' => 'Renee', 'apellido' => 'Schroeder', 'telefono' => '+1.574.452.5703', 'correo' => 'pouros.benton@example.com', 'direccion' => '52858 Michel Manor Suite 694', 'codigo_postal' => '05890-2325', 'ciudad' => 'Port Jillianside', 'estado' => 'Utah', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 30, 'id_usuario' => 46, 'id_empresa' => 2, 'nombre' => 'Agustin', 'apellido' => 'Reichel', 'telefono' => '816-350-5308', 'correo' => 'elody.schuster@example.com', 'direccion' => '16363 Katelin Cove', 'codigo_postal' => '24480', 'ciudad' => 'Candelarioside', 'estado' => 'Massachusetts', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 31, 'id_usuario' => 55, 'id_empresa' => 3, 'nombre' => 'Veda', 'apellido' => 'Wisoky', 'telefono' => '(731) 777-5223', 'correo' => 'zweimann@example.com', 'direccion' => '250 Veum Divide', 'codigo_postal' => '72294-0124', 'ciudad' => 'Aufderharfurt', 'estado' => 'Colorado', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 32, 'id_usuario' => 56, 'id_empresa' => 3, 'nombre' => 'Gaylord', 'apellido' => 'Emmerich', 'telefono' => '1-815-699-0755', 'correo' => 'mitchell.anastacio@example.com', 'direccion' => '85980 Feil Shore Suite 332', 'codigo_postal' => '15653', 'ciudad' => 'New Corbin', 'estado' => 'Rhode Island', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 33, 'id_usuario' => 57, 'id_empresa' => 3, 'nombre' => 'River', 'apellido' => 'Collier', 'telefono' => '+1 (469) 365-9161', 'correo' => 'nathanial59@example.org', 'direccion' => '49220 Wilfredo Well', 'codigo_postal' => '47856-1069', 'ciudad' => 'West Charley', 'estado' => 'Nebraska', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 34, 'id_usuario' => 58, 'id_empresa' => 3, 'nombre' => 'Allie', 'apellido' => 'Grant', 'telefono' => '(920) 223-7403', 'correo' => 'zaria65@example.net', 'direccion' => '7745 Gislason Well', 'codigo_postal' => '15430-9129', 'ciudad' => 'South Royceberg', 'estado' => 'Pennsylvania', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 35, 'id_usuario' => 59, 'id_empresa' => 3, 'nombre' => 'Cathy', 'apellido' => 'Leuschke', 'telefono' => '740.252.4711', 'correo' => 'ifadel@example.org', 'direccion' => '1588 Jacobs Wells Suite 406', 'codigo_postal' => '97053', 'ciudad' => 'North Alainaville', 'estado' => 'Indiana', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 36, 'id_usuario' => 60, 'id_empresa' => 3, 'nombre' => 'Dayton', 'apellido' => 'Daniel', 'telefono' => '+1-934-289-9878', 'correo' => 'jcarroll@example.net', 'direccion' => '583 Demario Summit Apt. 821', 'codigo_postal' => '07500-9299', 'ciudad' => 'Ankundington', 'estado' => 'Texas', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 37, 'id_usuario' => 61, 'id_empresa' => 3, 'nombre' => 'Ceasar', 'apellido' => 'Rice', 'telefono' => '+1 (817) 376-6977', 'correo' => 'audie.doyle@example.org', 'direccion' => '554 Bauch Port', 'codigo_postal' => '58813-5222', 'ciudad' => 'Schmidtport', 'estado' => 'Louisiana', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 38, 'id_usuario' => 62, 'id_empresa' => 3, 'nombre' => 'Zelda', 'apellido' => 'Beahan', 'telefono' => '+1-854-524-1389', 'correo' => 'thiel.chloe@example.net', 'direccion' => '53410 Aimee Camp Apt. 023', 'codigo_postal' => '71219', 'ciudad' => 'South Rebekaborough', 'estado' => 'Hawaii', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 39, 'id_usuario' => 63, 'id_empresa' => 3, 'nombre' => 'Herminio', 'apellido' => 'Stanton', 'telefono' => '336.202.3242', 'correo' => 'jesse.mayert@example.com', 'direccion' => '670 Littel Spur Apt. 238', 'codigo_postal' => '26021', 'ciudad' => 'Genehaven', 'estado' => 'Pennsylvania', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 40, 'id_usuario' => 64, 'id_empresa' => 3, 'nombre' => 'Lesly', 'apellido' => 'Langworth', 'telefono' => '820.749.2741', 'correo' => 'qgislason@example.org', 'direccion' => '6878 Kim Canyon Suite 170', 'codigo_postal' => '27804-9775', 'ciudad' => 'Dietrichbury', 'estado' => 'Oklahoma', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 41, 'id_usuario' => 65, 'id_empresa' => 3, 'nombre' => 'Prince', 'apellido' => 'Wolf', 'telefono' => '734.603.1076', 'correo' => 'chesley.morissette@example.net', 'direccion' => '9605 Selina Plaza Apt. 272', 'codigo_postal' => '91120-0771', 'ciudad' => 'Port Marianafort', 'estado' => 'Utah', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 42, 'id_usuario' => 66, 'id_empresa' => 3, 'nombre' => 'Stacey', 'apellido' => 'Schoen', 'telefono' => '225.290.8737', 'correo' => 'mcclure.mathias@example.org', 'direccion' => '1314 Harvey Fields Suite 634', 'codigo_postal' => '80583-5102', 'ciudad' => 'Shieldsport', 'estado' => 'Louisiana', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 43, 'id_usuario' => 67, 'id_empresa' => 3, 'nombre' => 'Ari', 'apellido' => 'Tromp', 'telefono' => '586-989-7398', 'correo' => 'gtoy@example.org', 'direccion' => '9453 Kerluke Ford Suite 050', 'codigo_postal' => '14425', 'ciudad' => 'Volkmanfurt', 'estado' => 'Maryland', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 44, 'id_usuario' => 68, 'id_empresa' => 3, 'nombre' => 'Andrew', 'apellido' => 'Von', 'telefono' => '727.365.7361', 'correo' => 'langworth.gwendolyn@example.com', 'direccion' => '9991 Mae Trace', 'codigo_postal' => '80070', 'ciudad' => 'Lincolnland', 'estado' => 'Indiana', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
            ['id_cliente' => 45, 'id_usuario' => 69, 'id_empresa' => 3, 'nombre' => 'Mose', 'apellido' => 'Greenholt', 'telefono' => '(918) 673-0141', 'correo' => 'joany.waelchi@example.org', 'direccion' => '8667 Steuber Heights Suite 708', 'codigo_postal' => '09000', 'ciudad' => 'North Magdalen', 'estado' => 'Florida', 'fecha_registro' => '2026-06-25 09:55:31', 'activo' => 1, 'tipo_identificacion' => null, 'numero_identificacion' => null, 'foto_perfil' => null, 'foto_ine' => null],
        ]);

        // Reactivar restricciones de clave foránea
        DB::statement('SET session_replication_role = DEFAULT');

        $this->command->info('✅ Datos importados correctamente.');
        $this->command->info('📌 Usuarios: password = "password"');
        $this->command->info('📌 Admin: juanprendas@admin.com / password');
        $this->command->info('📌 Admin: tulaempeños@admin.com / password');
        $this->command->info('📌 Admin: expressempeños@admin.com / password');
    }
}